variables:
- name: major
  value: '0'
- name: minor
  value: '1'
- name: extensionName
  value: 'Terraform'
- name: marketplaceServiceConnection
  value: 'marketplaceServiceConnection'
- name: publisherId
  value: 'ms-devlabs'
- name: publicExtensionName
  value: "Terraform"
- name: extensionId
  value: "custom-terraform-tasks"

name: $(major).$(minor)$(rev:.r)

trigger:
  branches:
    include:
    - main

pr: none

stages:
- stage: 'Build'
  jobs:
  - job: 'BuildPack'
    displayName: "Build and package"
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
    - task: Npm@1
      displayName: 'Install dependencies (root)'
      inputs:
        command: 'install'
        workingDir: '.'
    - task: Npm@1
      displayName: 'Install TerraformInstaller dependencies'
      inputs:
        command: 'custom'
        customCommand: 'run deps:npm:inst'
    - task: Npm@1
      displayName: 'Install TerraformTask dependencies'
      inputs:
        command: 'custom'
        customCommand: 'run deps:npm:tasks'
    - task: Npm@1
      displayName: 'Compile TerraformInstaller'
      inputs:
        command: 'custom'
        customCommand: 'run compile:inst'
    - task: Npm@1
      displayName: 'Compile TerraformTask'
      inputs:
        command: 'custom'
        customCommand: 'run compile:tasks'
    - task: Npm@1
      displayName: 'Prune dependencies'
      inputs:
        command: 'custom'
        customCommand: 'run deps:prune'
    - task: Npm@1
      displayName: 'Run webpack'
      inputs:
        command: 'custom'
        customCommand: 'run webpack'
    - task: CopyFiles@2
      displayName: 'Copy build artifacts'
      inputs:
        sourceFolder: '$(System.DefaultWorkingDirectory)/build'
        contents: '**'
        targetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish build artifacts'
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'terraform-extension'

