---
name: Unit Testing for TerraformTaskV4
on:
  pull_request:
    branches:
      - main
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  unit-test-v4:
    name: Unit Test V4 Task
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run Unit Tests
      run: |
        cd Tasks/TerraformTask/TerraformTaskV4
        npm install -include=dev
        npm test
  unit-test-v5:
    name: Unit Test V5 Task
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run Unit Tests
      run: |
        cd Tasks/TerraformTask/TerraformTaskV5
        npm install -include=dev
        npm test
